# Generated by Django 5.2.5 on 2025-08-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyslogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hostname', models.CharField(max_length=255)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('raw_message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Syslog Entries',
                'ordering': ['-received_at'],
            },
        ),
    ]
