# Generated by Django 5.2.5 on 2025-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetflowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_ip', models.CharField(max_length=255)),
                ('destination_ip', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=50)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Netflow Entries',
                'ordering': ['-received_at'],
            },
        ),
    ]
