# Generated by Django 5.2.5 on 2025-08-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_netflowentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetconsoleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_ip', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('raw_message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Netconsole Entries',
                'ordering': ['-received_at'],
            },
        ),
    ]
