# Generated by Django 5.2.5 on 2025-08-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_netconsoleentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netconsoleentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='netflowentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='syslogentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='netflowentry',
            name='destination_ip',
        ),
        migrations.RemoveField(
            model_name='netflowentry',
            name='source_ip',
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='dst_as',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='dst_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='dst_port',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='exporter_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='flow_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='flow_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='input_if',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='next_hop',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='observation_domain_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='output_if',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='packets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='raw',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='src_as',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='src_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='src_port',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='tcp_flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='template_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='tos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='vlan_id_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflowentry',
            name='vlan_id_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syslogentry',
            name='facility',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='syslogentry',
            name='severity',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='netconsoleentry',
            name='source_ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='netflowentry',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='netflowentry',
            name='protocol',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='syslogentry',
            name='app_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='syslogentry',
            name='hostname',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
