# Generated by Django 5.2.5 on 2025-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_alter_netconsoleentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnmpTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('version', models.CharField(db_index=True, max_length=8)),
                ('community', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('context_engine_id', models.CharField(blank=True, max_length=128, null=True)),
                ('context_name', models.CharField(blank=True, max_length=128, null=True)),
                ('trap_oid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('enterprise_oid', models.CharField(blank=True, max_length=255, null=True)),
                ('generic_trap', models.IntegerField(blank=True, null=True)),
                ('specific_trap', models.IntegerField(blank=True, null=True)),
                ('uptime', models.BigIntegerField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('security_level', models.CharField(blank=True, max_length=16, null=True)),
                ('auth_protocol', models.CharField(blank=True, max_length=16, null=True)),
                ('priv_protocol', models.CharField(blank=True, max_length=16, null=True)),
                ('engine_boots', models.IntegerField(blank=True, null=True)),
                ('engine_time', models.IntegerField(blank=True, null=True)),
                ('var_binds', models.JSONField(blank=True, null=True)),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
